name: Metrics
on:
  # Schedule updates (each hour) 
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: sample.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: cycool29
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kuala_Lumpur
      
      - name: Adjust image 
        run: |
          ls -A
          git pull
          cat ./sample.svg | grep -v "footer>\|These metrics include private contributions\|Last updated" | sed 's/height="367"/height="310"/g' | sed 's/0366d6/00ff00/g'  > ./github-metrics.svg
          rm ./sample.svg
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update GitHub Metrics"
          git push
